### ISSUE TITLE
import envVars  import timedRun

### ISSUE THREAD

**Issue by zenhumany** [MozillaSecurity/funfuzz#10]
Hi, MozillaSecurity teams:
when i run the funfuzz code , it reported cann't find the envVars, timedRun module

**Comment by jruderman** [comment]
What command are you running? Have you also cloned https://github.com/MozillaSecurity/lithium/ ?

**Comment by nth10sd** [comment]
You should have cloned https://github.com/MozillaSecurity/lithium/ adjacent to the funfuzz repo, i.e.: they should be in ~/lithium and ~/funfuzz if the parent directory is ~/.

If this still fails, please post the stacktrace.

**Comment by nth10sd** [comment]
This works properly if funfuzz and lithium repos are cloned adjacent to each other. Please file a new issue if it still happens for you.
