### ISSUE TITLE
[funfuzz] Run setup.py error on Mac OS X 10.6

### ISSUE THREAD

**Issue by armorunicorn** [MozillaSecurity/funfuzz#140]
I run "python setup.py install" and got a error on My MAC.This is the error message:
running install
running bdist_egg
running egg_info
writing src/funfuzz.egg-info/PKG-INFO
writing dependency_links to src/funfuzz.egg-info/dependency_links.txt
writing requirements to src/funfuzz.egg-info/requires.txt
writing top-level names to src/funfuzz.egg-info/top_level.txt
writing entry points to src/funfuzz.egg-info/entry_points.txt
reading manifest file 'src/funfuzz.egg-info/SOURCES.txt'
writing manifest file 'src/funfuzz.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
error: can't copy 'src/funfuzz/js/jsfunfuzz': doesn't exist or not a regular file

**Comment by nth10sd** [comment]
A bunch of things you can try:

* Update to the latest version of `setuptools` via pip (currently 36.6.0)
* Mac OS X 10.6 is not supported, try 10.12 and up
* Install funfuzz via pip: `pip install --upgrade <path to funfuzz>

**Comment by nth10sd** [comment]
Once again, 10.6 is not supported. Please feel free to file a new issue should this happen again on a later version of macOS (currently 10.13).
