### ISSUE TITLE
README.md instructions for first-time setup are not detailed enough

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#16]
I directed folks to use this repo and some commented that they spent half a day trying to get this to work.

The first piece of info that has to be made more obvious is that lithium should be checked out side-by-side to this repo.

**Comment by nth10sd** [comment]
And it turns out I merged the pull request in via the CLI, seems like I still need to get used to how git/github workflows interact with each other.

@jruderman I guess we can carry on the discussion here instead of in the PR.

**Comment by jruderman** [comment]
I added some checks to the python files that seem to be loaded first, so we shouldn't need the gigantic warning in the README any more.

https://github.com/MozillaSecurity/funfuzz/commit/c0079f0dffe3f072d6032d3fc0c743f5070d939d
