### ISSUE TITLE
Commandline argument -t "js" in bot.py is not recognized. But it is mentioned in the readme.md.

### ISSUE THREAD

**Issue by syedkhalid** [MozillaSecurity/funfuzz#185]
ubuntu@XXXXX~/PycharmProjects/funfuzz/src$ python -u -m funfuzz.loop_bot -b "--random" -t "js" --target-time 28800 | tee ~/log-loop_botPy.txt
localLoop #1!
Platform details: Linux  XXXXX-XXX 4.4.0-109-generic #132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018 x86_64 x86_64
hg version: Mercurial Distributed SCM (version 2.8.2)
gdb version: GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Python version: 2.7.6
Number of cores visible to OS: 4
Free space (GB): 220.89
Corefile size (soft limit, hard limit) is: (0, -1)
Usage: bot.py [options]

bot.py: error: no such option: -t
Something went wrong when calling: ['/usr/bin/python', '-u', '-m', 'funfuzz.bot', '-b', '--random', '-t', 'js', '--target-time', '28800']
CalledProcessError()
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/funfuzz/src/funfuzz/loop_bot.py", line 32, in loop_seq
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/usr/bin/python', '-u', '-m', 'funfuzz.bot', '-b', '--random', '-t', 'js', '--target-time', '28800']' returned non-zero exit status 2

**Comment by nth10sd** [comment]
Just needed a documentation update. Thanks!
