### ISSUE TITLE
[funfuzz] Zip up jsfunfuzz testcases before submitting to FuzzManager

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#229]
While we already compress wasm testcases found by funbind prior to reporting to FuzzManager, @tysmith pointed out that we should probably do the same for the legacy jsfunfuzz side too.

**Comment by tysmith** [comment]
I'd suggest using .zip for ease of use across operating systems even though zip likely won't give us the same compression ratios.

**Comment by nth10sd** [comment]
Good point, I'll keep using `.zip` then.

**Comment by nth10sd** [comment]
I pushed [a commit here](https://github.com/nth10sd/funfuzz/commit/15216374efd2277fe72ee938f736049bb3170768) on a branch to test things out first.

**Comment by nth10sd** [comment]
Thanks for [the review](https://github.com/nth10sd/funfuzz/commit/15216374efd2277fe72ee938f736049bb3170768#commitcomment-33161087) @tysmith !
