### ISSUE TITLE
I am trying fuzz firefox with code coverage, got some problems

### ISSUE THREAD

**Issue by 9k01** [MozillaSecurity/funfuzz#232]
Hello MozillaSecurity Team:
I am trying fuzz firefox with code coverage to get ***.info file to observe the fuzz coverage
my pc is slow,  i could not going to compile mozilla source code myself
https://developer.mozilla.org/en-US/docs/Mozilla/Testing/Measuring_Code_Coverage_on_Firefox

Here is my steps:
1.
i download 
https://taskcluster-artifacts.net/PuJAWDLyQUa4G1524NT3gQ/0/public/build/target.zip
with build info
https://queue.taskcluster.net/v1/task/PuJAWDLyQUa4G1524NT3gQ
2.
Unpack the target.zip->firefox.exe
dbclick run firefox.exe
about:buildconfig has Configure options  --enable-coverage
then run test.html
close firefox
no ***.info found on my pc, is there some wrong with my steps?

**Comment by nth10sd** [comment]
This repository is for fuzzing SpiderMonkey, and is not the correct place for solving your issue. Perhaps you'd like to ask on IRC at irc.mozilla.org and may be trying out `#developers` ?
