### ISSUE TITLE
A question of mozilla-central.

### ISSUE THREAD

**Issue by ty5491003** [MozillaSecurity/funfuzz#234]
Hi, I have a question.

My internet connection is so slow that i can't download mozilla-central by `hg clone https://hg.mozilla.org/mozilla-central/ ~/trees/mozilla-central/`. 

So can I download `mozilla-central-9420b5dc27e0.zip` by my browser from `https://hg.mozilla.org/mozilla-central/` and then unzip it to `~/trees/`? Does this work?

Thx, looking forward your reply!

**Comment by ty5491003** [comment]
I tried this way, and i got a errro when i run `python -u funfuzz/loop_bot.py -b "--random" --target-time 28800 | tee ~/log-loop_botPy.txt`:
```
INFO:__main__:Tue Dec  3 22:10:03 2019
INFO:__main__:Updating mozilla-central ...
INFO:__main__:WARNING: OSError hit:
INFO:__main__:Type of repository located at /export/nisl/trees/mozilla-central cannot be dete
rmined.
```
Will this error affect my subsequent work?

**Comment by nth10sd** [comment]
> So can I download `mozilla-central-9420b5dc27e0.zip` by my browser from `https://hg.mozilla.org/mozilla-central/` and then unzip it to `~/trees/`? Does this work?

No, it has to be a Mercurial repository. If you run `hg clone` with a recent hg, you should get:

```
$ hg clone https://hg.mozilla.org/mozilla-central mctest
applying clone bundle from https://hg.cdn.mozilla.net/mozilla-central/9420b5dc27e0cdf30a65b1b733400a970b3cb708.zstd-max.hg
adding changesets
```

Try downloading the *.hg file (note that the URL can change due to CDN reasons), then unbundling the file.

> Will this error affect my subsequent work?

Yes, especially for bisection, as funfuzz uses `hg bisect` to try and pinpoint the source of the issue.

**Comment by ty5491003** [comment]
@nth10sd I get it, thanks for your reply.
