### ISSUE TITLE
pip requirements not specified

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#35]
We should specify what pip requirements are needed, or at least update the docs for a start.

pip packages needed: requests, numpy (from FuzzManager), boto

**Comment by nth10sd** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1273350 for original issue

**Comment by choller** [comment]
Please do not list FuzzManager dependencies in your manual. Instead point to the FuzzManager requirements.txt file which already lists these.
