### ISSUE TITLE
Fuzzmanager TypeError unexpected keyword argument 'widget'

### ISSUE THREAD

**Issue by kazenomamani210** [MozillaSecurity/funfuzz#37]
my os is ubuntu 14.04 64bit.

Step to reproduce

1. Go to directory /FuzzManager/server and run "python manage.py runserver"

2. Go to 127.0.0.1:8000 and I will see TypeError message.

I posted my Traceback on pastbin. Please check it.

https://pastebin.mozilla.org/8872030

--------------------------------------------
This is local Variable.

/usr/local/lib/python2.7/site-packages/rest_framework/fields.py in __init__

Variable 	Value
self 	

CharField(required=False, widget=<class 'django.forms.widgets.Textarea'>)

kwargs 	

{'required': False, 'widget': <class 'django.forms.widgets.Textarea'>}

------------------------------------------------

In order to fix this, what should I do?

I think there are so many errors on funfuzz... Probably it is impossible to configure funfuzz.

**Comment by kazenomamani210** [comment]
widget = class 'django.forms.widgets.Textarea' 

widget became empty because I used less-than sign <

**Comment by nth10sd** [comment]
@kazenomamani210, looking at the stack, next time you might want to file FuzzManager issues here: https://github.com/MozillaSecurity/FuzzManager/issues

About this one, @choller any ideas?

**Comment by choller** [comment]
@kazenomamani210 Can you please post the versions of Django and djangorestframework ?

Did you perform any other steps like submitting something, prior to encountering this error?

**Comment by kazenomamani210** [comment]
I am sorry for posting fuzzmanager issue on this.

-----------------------------------------------

Django Version: 	1.7.11

djangorestframework==3.3.3

------------------------------------------------

Before configure fuzzmanager, I used jsfunfuzz because I didn't know that I should configure fuzzmanager in order to receive error report properly. 

Maybe is that the route cause? If so, probably I need to uninstall funfuzz and fuzzmanager and re-install everything...

**Comment by choller** [comment]
No, the problem is likely that you have the wrong dependencies. You use djangorestframework 3.x.x while requirements.txt specifies 2.4.4. Please try a 2.x version (maybe even 2.4.x). They might have changed a lot of API in 3.x which we haven't adapted yet.

**Comment by kazenomamani210** [comment]
Thank you for your advice. I will change immediately.

**Comment by kazenomamani210** [comment]
@choller This issue has been solve by installing djangorestframework 2.4.4. FuzzManager will not work on ver. 3.x.x.
