### ISSUE TITLE
How to use funfuzz dom tool?

### ISSUE THREAD

**Issue by kazenomamani210** [MozillaSecurity/funfuzz#38]
step to reproduce 

1.Run a command "funfuzz/util/downloadBuild.py"

2. "build" directory will be installed.

3. Run a command "funfuzz/dom/automation/loopdomfuzz.py build"

4. Error message will be displayed.

-----------------------------------------------
my error message

browserDir does not appear to be a valid build: '/home/kaze/build'

(browserDir should be an objdir for a local build, or a Tinderbox build downloaded with downloadBuild.py)

------------------------------------------------

So, why did this message appear even if I used "downloadBuild.py"?

I tried another way, but I failed...

funfuzz/dom/automation/loopdomfuzz.py ~/build/dist/bin/firefox

**Comment by nth10sd** [comment]
@jruderman would be the best person for this...

**Comment by kazenomamani210** [comment]
@nth10sd Can you use funfuzz dom tool?

**Comment by jruderman** [comment]
Sorry about that. A recent change (9b8e1f47d558e168c30b2c25b09df0c53c4b18b0) made it so DOMFuzz requires downloadBuild.py --want-tests, but I hadn't updated the instructions for DOMFuzz to include that flag.
