### ISSUE TITLE
[jsfunfuzz] Update parameters to evaluate

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#42]
I was reading through [the following](https://github.com/MozillaSecurity/funfuzz/blob/20cfc8c/js/jsfunfuzz/gen-type-aware-code.js#L165) after reading that newContext in evaluate is [now removed](https://hg.mozilla.org/mozilla-central/rev/1258a697a4bb).

@jruderman, besides newContext, are saveFrameChain, elementProperty and sourcePolicy still used?

**Comment by jruderman** [comment]
* newContext: removed in https://hg.mozilla.org/mozilla-central/rev/1258a697a4bb
* saveFrameChain: removed in https://hg.mozilla.org/mozilla-central/rev/d835e1ad4222
* elementProperty: renamed to elementAttributeName in https://hg.mozilla.org/mozilla-central/rev/8bcd545cf484
* sourcePolicy: replaced with the boolean sourceIsLazy, in https://hg.mozilla.org/mozilla-central/rev/95391b25bc11
