### ISSUE TITLE
Documentation for compileShell

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#5]
We need some basic documentation in the README.md for using compileShell.

**Comment by nth10sd** [comment]
I've added more documentation in rev b105f09.

**Comment by jruderman** [comment]
I'd prefer for this to be separate from js/README.md, so it's not in the way of people looking for information about the fuzzer. Can you move this new documentation to somewhere like js/compileShell.md? We can change the sentence starting with "To test an existing SpiderMonkey shell..." to link to the compileShell documentation.

The "examples" section seems excessive.

**Comment by nth10sd** [comment]
There seems to be lots of files in this directory we can write docs for. compileShell, jsfunfuzz, compareJIT, shellFlags, ... However, there is js/jsfunfuzz/ directory that we can move the "What jsfunfuzz does" to. (and link to them from README.md here) Should we elaborate more on jsfunfuzz in the future, it seems like it might be a better place there.

I can move examples into examples-compileShell.md. I think the more examples there are, the better, though I agree it may be too verbose for README.md. The FAQ can also be moved to, if needed. (maybe to faq-compileShell.md?)

Thoughts?

**Comment by nth10sd** [comment]
Moved FAQ section in rev 2b50d42.
