### ISSUE TITLE
How to configure funfuzz?

### ISSUE THREAD

**Issue by greg5678** [MozillaSecurity/funfuzz#51]
I have looked in each file (including the settings.py file) but I have yet to see a configuration file. I would like to set the path of firefox but I see no where I can do that?

**Comment by jruderman** [comment]
funfuzz doesn't use a configuration file. Instead, domInteresting.py asks you to pass in the path to a Firefox build as one of its arguments. If you run bot.py, it can download or compile Firefox for you. (Same for js shells with jsInteresting.py, etc)

**Comment by greg5678** [comment]
Where is the dominteresting.py file located?

**Comment by greg5678** [comment]
So what part of the file do I edit to place firefox's location(path)?

**Comment by jruderman** [comment]
See https://github.com/MozillaSecurity/funfuzz/blob/master/dom/README.md :)

I don't recommend using an ordinary release build of Firefox. I've mostly used it with various kinds of debug builds and ASan builds.

**Comment by greg5678** [comment]
I have been trying to download Firefox Asan for my mac but when I run it I get this. I got Firefox from here. https://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-linux64-asan-debug/
sudo ./firefox
Password:
./firefox: ./firefox: cannot execute binary file
and 
sudo ./firefox-bin
./firefox-bin: ./firefox-bin: cannot execute binary file

**Comment by nth10sd** [comment]
You're trying to run a Linux ASan build on Mac, which does not work.

**Comment by greg5678** [comment]
Is there a Firefox ASan build for Mac?

**Comment by nth10sd** [comment]
It doesn't seem to be available on https://ftp.mozilla.org/pub/firefox/tinderbox-builds/ so you would probably have to compile it yourself:

https://developer.mozilla.org/en-US/docs/Mozilla/Testing/Firefox_and_Address_Sanitizer

**Comment by greg5678** [comment]
So like this.
svn co -r $REV https://llvm.org/svn/llvm-project/llvm/trunk llvm
cd llvm
export LLVM_HOME=`pwd` # We will refer to this variable later during the build.
(cd tools && svn co -r $REV https://llvm.org/svn/llvm-project/cfe/trunk clang)
(cd projects && svn co -r $REV https://llvm.org/svn/llvm-project/compiler-rt/trunk compiler-rt)
mkdir build
cd build
cmake -DLLVM_ENABLE_LIBCXX=ON $LLVM_HOME
make -j6
# Combined .mozconfig file for ASan on Linux+Mac

mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/objdir-ff-asan

# Adjust this to the number of CPU cores + 2
mk_add_options MOZ_MAKE_FLAGS=-j10

# Enable ASan specific code and build workarounds
ac_add_options --enable-address-sanitizer

# Ensure you set this to your LLVM_HOME path
export LLVM_HOME="/path/to/your/llvm"

# Set CC/CXX based on LLVM_HOME
export CC="$LLVM_HOME/build/bin/clang"
export CXX="$LLVM_HOME/build/bin/clang++"

# This will ensure the symbolizer is packaged with the binary
export LLVM_SYMBOLIZER="$LLVM_HOME/build/bin/llvm-symbolizer"

# Add ASan to our compiler flags
export CFLAGS="-fsanitize=address -Dxmalloc=myxmalloc -fPIC"
export CXXFLAGS="-fsanitize=address -Dxmalloc=myxmalloc -fPIC"

# Additionally, we need the ASan flag during linking. Normally, our C/CXXFLAGS would
# be used during linking as well but there is at least one place in our build where
# our CFLAGS are not added during linking.
# Note: The use of this flag causes Clang to automatically link the ASan runtime :)
export LDFLAGS="-fsanitize=address"

# These three are required by ASan
ac_add_options --disable-jemalloc
ac_add_options --disable-crashreporter
ac_add_options --disable-elf-hack

# Keep symbols to symbolize ASan traces later
export MOZ_DEBUG_SYMBOLS=1
ac_add_options --enable-debug-symbols
ac_add_options --disable-install-strip

# Settings for an opt build (preferred)
# The -gline-tables-only ensures that all the necessary debug information for ASan
# is present, but the rest is stripped so the resulting binaries are smaller.
ac_add_options --enable-optimize="-O2 -gline-tables-only"
ac_add_options --disable-debug

# Settings for a debug+opt build
#ac_add_options --enable-optimize
#ac_add_options --enable-debug

# MacOSX only: Uncomment and adjust this path to match your SDK ac_add_options --with-macos-sdk=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk
./mach build

**Comment by jruderman** [comment]
Last time I tried the instructions on https://developer.mozilla.org/en-US/docs/Mozilla/Testing/Firefox_and_Address_Sanitizer on Mac, I ran into a bunch of problems. My current mozconfig-asan, which includes a bunch of workarounds I don't fully understand, is at https://gist.github.com/jruderman/8b2acb60d120843fdcd7a3bb3937435e. I use the llvm that comes with xcode for building Firefox, but the llvm-symoblizer from a local build at ~/llvm/build-release/bin/llvm-symbolizer.

**Comment by greg5678** [comment]
Where do I put the file and what do I call it?
cd ~/trees
ls
mozilla-central
AUTHORS			docshell		mozilla-config.h.in
Android.mk		dom			netwerk
CLOBBER			editor			nsprpub
GNUmakefile		embedding		old-configure.in
LEGAL			extensions		other-licenses
LICENSE			gfx			parser
Makefile.in		gradle			probes
README.txt		gradle.properties	python
accessible		gradlew			rdf
aclocal.m4		hal			release
addon-sdk		image			security
b2g			intl			services
browser			ipc			settings.gradle
build			js			startupcache
build.gradle		layout			storage
caps			mach			test.mozbuild
chrome			media			testing
client.mk		memory			toolkit
client.py		mfbt			tools
config			mobile			uriloader
configure.in		modules			view
configure.py		moz.build		widget
db			moz.configure		xpcom
devtools		mozglue			xpfe
BreslinD:mozilla-central Student$ ls
AUTHORS			docshell		mozilla-config.h.in
Android.mk		dom			netwerk
CLOBBER			editor			nsprpub
GNUmakefile		embedding		old-configure.in
LEGAL			extensions		other-licenses
LICENSE			gfx			parser
Makefile.in		gradle			probes
README.txt		gradle.properties	python
accessible		gradlew			rdf
aclocal.m4		hal			release
addon-sdk		image			security
b2g			intl			services
browser			ipc			settings.gradle
build			js			startupcache
build.gradle		layout			storage
caps			mach			test.mozbuild
chrome			media			testing
client.mk		memory			toolkit
client.py		mfbt			tools
config			mobile			uriloader
configure.in		modules			view
configure.py		moz.build		widget
db			moz.configure		xpcom
devtools		mozglue			xpfe

**Comment by jruderman** [comment]
Put it wherever you want, and use the MOZCONFIG env var to tell 'make -f client.mk' where to find it. Then you can run something like:

cd ~/trees/mozilla-central/ && MOZCONFIG=~/mozconfig/mozconfig-asan time make -f client.mk

**Comment by jruderman** [comment]
Btw, here's the bash script I used to build llvm: https://gist.github.com/jruderman/2c16de3056970c0bef7109a668eea9e1

**Comment by greg5678** [comment]
How do I use the MOZCONFIG env var?

**Comment by jruderman** [comment]
If you're using bash, the example in my previous comment shows one way to use the env var.

**Comment by greg5678** [comment]
So like this? cd ~/trees/mozilla-central/ && MOZCONFIG=~/mozconfig/mozconfig-asan time make -f client.mk

**Comment by jruderman** [comment]
Yes, that's what I use (with my various mozconfig files stored in ~/mozconfig/)

**Comment by greg5678** [comment]
so I should create a directory called mozconfig using the command sudo mkdir ~/mozconfig. Then create a file called mozconfig-asan using the command sudo touch mozconfig-asan. Then run the command cd ~/trees/mozilla-central/ && MOZCONFIG=~/mozconfig/mozconfig-asan time make -f client.mk

**Comment by jruderman** [comment]
You shouldn't need sudo at all to build or run Firefox. You will probably have to experiment with the contents of your mozconfig file.

**Comment by greg5678** [comment]
So are the commands in my last post (other than not needing sudo)?

**Comment by jruderman** [comment]
Hopefully! And keep in mind that you need to fill in mozconfig-asan with probably a mix of what you find on https://developer.mozilla.org/en-US/docs/Mozilla/Testing/Firefox_and_Address_Sanitizer and the gist I linked to earlier. ("touch" just creates an empty file.)

**Comment by greg5678** [comment]
Should I use nano instead of touch?

**Comment by greg5678** [comment]
Should I have to tweak this line 
`mk_add_options MOZ_OBJDIR=/Users/jruderman/builds/$srcdirname-asan-opt` because my location's directory has a different path?
https://gist.github.com/jruderman/8b2acb60d120843fdcd7a3bb3937435e

**Comment by greg5678** [comment]
Should the ~/mozconfig director be inside the ~/trees/mozilla-central directory?

**Comment by jruderman** [comment]
Yes, nano should work.

Yes, you should tweak the MOZ_OBJDIR line.

No, don't place mozconfig shouldn't be inside ~/trees/mozilla-central/ -- you generally shouldn't put extra files in repos in case you have to blow them away, diff, etc. You don't have to put it exactly where I put it, as long as you set the MOZCONFIG env var to point to where you put it.

**Comment by greg5678** [comment]
Ok!

**Comment by greg5678** [comment]
I don't have a builds directory. What is suppose to be in the builds directory? 
mk_add_options MOZ_OBJDIR=/Users/jruderman/builds/$srcdirname-asan-opt

**Comment by jruderman** [comment]
The "builds" directory should be created automatically when you invoke make, or you can create it as an empty directory now. You should end up with a "~/builds/mozilla-central-asan-opt/" if everything works correctly.

Btw, you might find that you can get faster help with funfuzz in #fuzzing and with the Firefox build system in #introduction (both on irc.mozilla.org).

**Comment by nth10sd** [comment]
> You should end up with a "~/builds/mozilla-central-asan-opt/" if everything works correctly.

I'm assuming here that everything had worked correctly in the 1.5 years since. Moreover, DOMFuzz has been removed from funfuzz. Closing.
