### ISSUE TITLE
ValueError in autoBisect

### ISSUE THREAD

**Issue by josephbisch** [MozillaSecurity/funfuzz#56]
I get a ValueError message in FuzzManager under the Metadata heading after a crash is found. I am on Arch Linux. Using the Python shell, I get the following result.

```
>>> print platform.linux_distribution()
('', '', '')
```

The ValueError message:

autoBisectLog=Traceback (most recent call last): File "/home/joseph/funfuzz/autobisect-js/autoBisect.py", line 881, in <module> main() File "/home/joseph/funfuzz/autobisect-js/autoBisect.py", line 856, in main options = parseOpts() File "/home/joseph/funfuzz/autobisect-js/autoBisect.py", line 164, in parseOpts earliestKnownQuery = kbew.earliestKnownWorkingRev(options.buildOptions, options.paramList + extraFlags, options.skipRevs) File "/home/joseph/funfuzz/autobisect-js/knownBrokenEarliestWorking.py", line 144, in earliestKnownWorkingRev if sps.isLinux and float(platform.linux_distribution()[1]) > 15.04: ValueError: could not convert string to float:

This seems like a bug, because any Linux distro that defines itself as being a version > 15.04 makes the if statement true, whether or not it is a version of Ubuntu. And of course it results in an error like the one I experienced if the version isn't parsable into a float.

**Comment by nth10sd** [comment]
> because any Linux distro that defines itself as being a version > 15.04 makes the if statement true, whether or not it is a version of Ubuntu.

True, though funfuzz assumes Ubuntu by default. There is also insufficient testing with Fedora, for example.

I will fix this by moving to m-c rev bcacb5692ad9 as the earliest known working rev for all Linuxes, as it seems to be the earliest that works with GCC 5.
