### ISSUE TITLE
we should do some more try to find git path in windows

### ISSUE THREAD

**Issue by lovesuae** [MozillaSecurity/funfuzz#66]
in line 32 of funfuzz\util\reposUpdate.py:
    GITBINARY = os.path.normpath(os.path.join(os.getenv('PROGRAMFILES(X86)'), 'Git', 'bin', 'git.exe'))

in windows 32bit, os.getenv('PROGRAMFILES(X86)') returns None
in windows 64bit, now git recommend to install 64bit of git, so git is not in PROGRAMFILES(X86) directory,
so both in 32bit and 64bit windows, this line will run error:
Traceback (most recent call last):
  File "c:\funfuzz\funfuzz\util\reposUpdate.py", line 35, in <module>
    GITBINARY = os.path.normpath(os.path.join(os.getenv('PROGRAMFILES(X86)'), 'G
it', 'bin', 'git.exe'))
  File "c:\mozilla-build\python\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "c:\mozilla-build\python\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
Something went wrong when calling: ['c:\\mozilla-build\\python\\python.exe', '-u
', 'c:\\funfuzz\\funfuzz\\util\\reposUpdate.py']
CalledProcessError()
Traceback (most recent call last):
  File "funfuzz/loopBot.py", line 41, in loopSequence
    subprocess.check_call(cmd)
  File "c:\mozilla-build\python\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['c:\\mozilla-build\\python\\python.exe', '-u', 'c:
\\funfuzz\\funfuzz\\util\\reposUpdate.py']' returned non-zero exit status 1

**Comment by nth10sd** [comment]
The last time I tried, MozillaBuild 2.2.0 has issues with 64-bit Git installed (only support for 32-bit Git was implemented). Currently, MozillaBuild is on a hiatus, so I'd rather wait it out for the next version supporting msys2 to be ready, then we can work on this more.

In the meantime, I think 32-bit Git still works in MozillaBuild...

**Comment by nth10sd** [comment]
Rev 0af65320fc23c9acc39e86911d92b6430f9c96ce added support for detecting 64-bit Git as well, which no longer runs into the same issue I used to, in late 2016.
