### ISSUE TITLE
getRepoHashAndId should use striped input data: updateDefault

### ISSUE THREAD

**Issue by lovesuae** [MozillaSecurity/funfuzz#69]
funfuzz\util\hgCmds.py line 88
updateDefault = raw_input('Not on default tip! ' +
                                  'Would you like to (a)bort, update to (d)efault, or (u)se this rev: ')
        
        updateDefault = updateDefault.strip() //add this line
        if updateDefault == 'a':
            print 'Aborting...'
            sys.exit(0)
        elif updateDefault == 'd':
            subprocess.check_call(['hg', '-R', repoDir, 'update', 'default'])
            onDefault = True
        elif updateDefault == 'u':
            hgLogTmplList = ['hg', '-R', repoDir, 'log', '-r', 'parents()', '--template',
                             '{node|short} {rev}']
        else:
            raise Exception('Invalid choice.')
        hgIdFull = sps.captureStdout(hgLogTmplList)[0]

**Comment by nth10sd** [comment]
Good spot, raw_input entries should probably have their whitespaces removed.
