### ISSUE TITLE
[funfuzz] compileShell fails on Fedora due to autoconf 2.13 binary name discrepancy

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/funfuzz#9]
compileShell fails on Fedora because it is "autoconf-2.13" there, not "autoconf2.13" as per Ubuntu.

Thanks :Waldo for helping to test here.

**Comment by jruderman** [comment]
client.mk solves this by calling "which autoconf-2.13 autoconf2.13 autoconf213" to find out which one exists on PATH:

https://dxr.mozilla.org/mozilla-central/source/client.mk#60

**Comment by nth10sd** [comment]
I worked around this issue in rev eafec9827d8598e1f945bad8a97ec2d8534d3e52 but I agree that this should be fixed the way client.mk does it.

**Comment by nth10sd** [comment]
Worked around, patches accepted for now.
